#!/bin/bash
set -e

# Update desktop database
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if [ -x /usr/bin/update-desktop-database ]; then
        update-desktop-database -q
    fi
fi

#DEBHELPER#

exit 0
